---
title: "LarsHal_vignette"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r}
library(hal9001)
n <- 500
p <- 3
x <- xmat <- matrix(rnorm(n * p), n, p)
y <- sin(x[, 1]) + rnorm(n, mean = 0, sd = 0.2)

test_n <- 500
test_x <- matrix(rnorm(test_n * p), test_n, p)
test_y <- sin(test_x[, 1]) #* sin(test_x[, 2]) 
# + rnorm(
#   test_n,
#   mean = 0,
#   sd = 0.2
# )
data <- data.frame(x, y)
colnames(data) <- c("X1", "X2", "X3", "Y")


test_that("Check formula", {
  formula <- formula_hal("Y ~ h(X1) + h(X2) + h(X3)", data, num_knots = 5)
  expect_true(length(formula$basis_list) == p*5)
})

test_that("Check formula", {
  formula <- formula_hal("Y ~ .", data, num_knots = 5)
  expect_true(length(formula$basis_list) == p*5)
})

test_that("Check formula", {
  formula <- formula_hal("Y ~ h(X1,X2)", data, num_knots = c(3,3))
  print(length(formula$basis_list))
   print((formula$basis_list))
  expect_true(length(formula$basis_list) == 6)
})




```



```{r}
formula <- formula_hal("Y ~ i(.) + i(.,.)", data, num_knots = 3)
upper<- formula$upper.limits
lower<- formula$lower.limits


test_that("Check formula", {
  expect_true(all(upper==Inf) && all(lower==0))
})

formula <- formula_hal("Y ~ h(.) + h(.,.)", data, num_knots = 3)
upper<- formula$upper.limits
lower<- formula$lower.limits


test_that("Check formula", {
  expect_true(all(upper==Inf) && all(lower==-Inf))
})
formula <- formula_hal("Y ~ d(.) + d(.,.)", data, num_knots = 3)
upper<- formula$upper.limits
lower<- formula$lower.limits

test_that("Check formula", {
  expect_true(all(upper==0) && all(lower==-Inf))
})

```










