# Generated by using Rcpp::compileAttributes() -> do not edit by hand Generator
# token: 10BE3573-1514-4C36-9D1C-5A225CD40393

index_first_copy <- function(X) {
    .Call("_mangolassi_index_first_copy", PACKAGE = "mangolassi", X)
}

column_compare <- function(X, col_1, col_2) {
    .Call("_mangolassi_column_compare", PACKAGE = "mangolassi", X, col_1, col_2)
}

or_duplicate_columns <- function(X, cols) {
    invisible(.Call("_mangolassi_or_duplicate_columns", PACKAGE = "mangolassi", X, 
        cols))
}

lassi_predict <- function(X, beta) {
    .Call("_mangolassi_lassi_predict", PACKAGE = "mangolassi", X, beta)
}

update_coord <- function(X, resids, beta, lambda, j) {
    invisible(.Call("_mangolassi_update_coord", PACKAGE = "mangolassi", X, resids, 
        beta, lambda, j))
}

lassi_fit_cd <- function(X, y, lambda, nsteps) {
    .Call("_mangolassi_lassi_fit_cd", PACKAGE = "mangolassi", X, y, lambda, nsteps)
}

make_basis_list <- function(X_sub, cols) {
    .Call("_mangolassi_make_basis_list", PACKAGE = "mangolassi", X_sub, cols)
}

meets_basis <- function(X, row_num, cols, cutoffs) {
    .Call("_mangolassi_meets_basis", PACKAGE = "mangolassi", X, row_num, cols, cutoffs)
}

evaluate_basis <- function(basis, X, x_basis, basis_col) {
    invisible(.Call("_mangolassi_evaluate_basis", PACKAGE = "mangolassi", basis, 
        X, x_basis, basis_col))
}

make_design_matrix <- function(X, blist) {
    .Call("_mangolassi_make_design_matrix", PACKAGE = "mangolassi", X, blist)
}

