# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

col_counts <- function(X) {
    .Call('mangolassi_col_counts', PACKAGE = 'mangolassi', X)
}

lassi_predict <- function(X, beta) {
    .Call('mangolassi_lassi_predict', PACKAGE = 'mangolassi', X, beta)
}

update_coord <- function(X, resids, beta, lambda, j) {
    invisible(.Call('mangolassi_update_coord', PACKAGE = 'mangolassi', X, resids, beta, lambda, j))
}

lassi_fit_cd <- function(X, y, lambda, nsteps) {
    .Call('mangolassi_lassi_fit_cd', PACKAGE = 'mangolassi', X, y, lambda, nsteps)
}

