# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Find Copies of Columns
#'
#' Index vector that, for each column in X, indicates the index of the first
#' copy of that column
#'
index_first_copy <- function(X) {
    .Call('_hal9001_index_first_copy', PACKAGE = 'hal9001', X)
}

#' Compute Column Ranks
#'
#' \code{TRUE} iff col_1 is strictly less than col_2 in the ordering scheme
#'
column_compare <- function(X, col_1, col_2) {
    .Call('_hal9001_column_compare', PACKAGE = 'hal9001', X, col_1, col_2)
}

#' Reorder Columns of X
#'
#' ORs the columns of X listed in cols and places the result in column col[1]
#'
or_duplicate_columns <- function(X, cols) {
    invisible(.Call('_hal9001_or_duplicate_columns', PACKAGE = 'hal9001', X, cols))
}

lassi_predict <- function(X, beta) {
    .Call('_hal9001_lassi_predict', PACKAGE = 'hal9001', X, beta)
}

update_coord <- function(X, resids, beta, lambda, j) {
    invisible(.Call('_hal9001_update_coord', PACKAGE = 'hal9001', X, resids, beta, lambda, j))
}

lassi_fit_cd <- function(X, y, lambda, nsteps) {
    .Call('_hal9001_lassi_fit_cd', PACKAGE = 'hal9001', X, y, lambda, nsteps)
}

make_basis_list <- function(X_sub, cols) {
    .Call('_hal9001_make_basis_list', PACKAGE = 'hal9001', X_sub, cols)
}

meets_basis <- function(X, row_num, cols, cutoffs) {
    .Call('_hal9001_meets_basis', PACKAGE = 'hal9001', X, row_num, cols, cutoffs)
}

evaluate_basis <- function(basis, X, x_basis, basis_col) {
    invisible(.Call('_hal9001_evaluate_basis', PACKAGE = 'hal9001', basis, X, x_basis, basis_col))
}

make_design_matrix <- function(X, blist) {
    .Call('_hal9001_make_design_matrix', PACKAGE = 'hal9001', X, blist)
}

